### PR TITLE
Roundcube v1plus

### PR DESCRIPTION
**Pull request by SimonHoenscheid**
Make module  it usable with Roundcube v1.0+ with new config structure

### CODE REVIEW

**Comment by lazyfrosch** [comment]
We should take care about a compat layer for "old" Roundcube 0.x

**Comment by SimonHoenscheid** [comment]
I'm not shure. Old versions have lots of Security Issues. I would like to deprecate everything before v1.0. The Last Release of 0.x was in October 2013.

**Comment by lazyfrosch** [comment]
Sure that, but it should be cheap, since only the Array name seems to have changed.

Plus there are several "supported" version of Roundcube 0.x out there, look here: https://launchpad.net/ubuntu/+source/roundcube

**Comment by lazyfrosch** [comment]
Could you compare our config template against the default shipped one from Roundcube latest, and update it?

**Comment by SimonHoenscheid** [comment]
Sure. I will find some time for that

**Pull request closed without merging**
